travis:
  secure:
    BINSTAR_TOKEN: 3yEhch9Dp2Vl6gio/FUUM0a2xwIWvwF6QG1neE3uWdRuMVnz1lp2wyJS1t8n/n7Fk7vRX1X0qyl0jH0dO66swT1HBZhtEHgT+KkrGRA9di9vx6GiBGULotcwC3GMYxnsQC7Gb48mfq93qHe52Ki4l0A7kxyH0E4mhvAo3Rk2Hvih54Q8FRewVDY3Ap+OOztPaKYq0dY0x/8KeNSAyB7BkpICDyxS6JFJN5ggGLSTp1+K4JeiuXt1Zj3UNJzyLlykQfTG9sCN2JFj4BPbXs9PCIElUMWFOyF4x6ITBlREm6rkm3xEXtFlt4s6/8Buy7w9wolxW97Y4V5Q0QlIXgB3QcyXeRh54ypHqV30YoyGInCD/WvGQZ4tVW1gpc35bL6HBiVxBY0RN67FjmFXTZrhLeJwtgAnP6FNhOdjwD1APD0gf2HaIRGiMgp5kAHay6uKxWxVn0NjOVf25/iNhwQ+35zoV7iUI+BeOWqKFQp5jpD8ps91gRCHdjbCDpczt2bcsz0EiprcZTJ7A1FLl3D8577qNFEPZD6pZr1eDG1peuyFKvQdwlOGjYMa0d7LgmC1q/WI6KZ89bQIEWDD7L1gJXlGyxAtYp9C0RkDUCfoa/3QPDsdqrGF3thsAODazgrKF4sJxzcyK9nltFiINko7PCIaF0MepyfR6Epq8hhcnTY=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
