travis:
  secure:
    BINSTAR_TOKEN: r+UFjQR6YyNNl4QTvEl0qYVjuNjuIsvREDOSiMWw2+NcrxIhlE4PiQ4lpxnGt3TfV8u/CqJgPnyVmwM6RaUfYTWgde2jVfrrShIrYgnn/qtjf5Sd9yoUPudZT9NdieZHPDMVVabS3mSPe5jyUgAJaTLF7Xn1mof1rulNeKLvKyTWmnNeXPqO5+sitaYHij11EgkQAlcqU5xQzT99nadoVr647zS3UhVCymU8sEm+JkYgjvHF/1MpmCwLAUz1uewIVJpvIE/wPzpBR8vL2XxrhxevLoBt44UAdOFk0oeNMcvJAS9+78p6LEfGhZ4dr2eKk9nvsbIdq1taTcSMYSsJPhKh9Mneaww33nkIeiN5EbsKY7mYKWRgYoOLX2+dXtpt0+k71D3ck7o+16SqwtBF+iNRGGh2DxftUr/YVyLl6lCAQPEupQ4F2OsibHnEu/pQfx4X5IgTeM3iQghsncVa8pmCvpqHvkg0TQA6Rihc4xz5JNn5wP2l8/V4OKtlE6kAAsMuWeMv6RWW5Yy7q3U+W5Sor4nS3LYKFIMynahH12TDsng+2kFSWVqsiFNYYsH4c6VdAy70sbgQdoFOAH3WBGIbosh2kFiZYLELLmJMr5G7H8OW0ImkNoDceKj3mL53mA2oXWk+/YJ9IfcwQKg6TusQs8ZGgbLTyoneXlzfmbc=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
